### PR TITLE
Led: Clear interval after animation

### PR DESCRIPTION
**Pull request by scottgonzalez**
Animation intervals weren't cleared until another animation started or `.stop()` was called. As a result, once the animation completed, the interval would keep running and the `step` and `complete` callbacks would be called repeatedly.

### CODE REVIEW

**Comment by dtex** [comment]
Should there be a test in the extended group to catch possible regression? It could be a separate issue/PR.

**Comment by scottgonzalez** [comment]
I'll update this tonight, now that #670 has landed.

**Comment by rwaldron** [comment]
Thanks @scottgonzalez!

**Comment by scottgonzalez** [comment]
That actually rebased cleanly :-)

**Comment by rwaldron** [comment]
Needs a test that confirms stop() is called

**Comment by scottgonzalez** [comment]
I added some basic tests. I'll flesh these out more in #724 after there's some discussion there.

**Pull request merged**
