### PR TITLE
Pcf8591 analog out

### PR DESCRIPTION
**Pull request by CzechUavGuy**
Added possibility for PCF8591 to output analog value. Needs code review - see comments in code.

### CODE REVIEW

**Comment by rwaldron** [comment]
LGTM, but needs tests. I might just write the test myself to ease back into work (I've been away for 8 weeks). Let me know if you want to write the tests or if I should. Here's where they'd go: https://github.com/rwaldron/johnny-five/blob/master/test/expander.js#L1982-L2156

**Comment by fivdi** [comment]
Is this really a good idea? The [PCF8591](https://www.nxp.com/documents/data_sheet/PCF8591.pdf) has a D/A converter that converts digital values to their corresponding analog voltage. The analog voltage can be more or less any voltage. It's not the same as PWM where the output voltage is either 0V or VDD where VDD is typically 5V.

Although the technique used by this PR will almost certainly work, reusing the PWM mode for DAC will likely result in confusion. For example, it's easy to set the brightness of an LED using PWM. Setting the brightness of an LED using DAC is more complex. If the PWM mode is reused for DAC, Johnny-Five will think that the pin supports PWM, but it doesn't.

**Comment by soundanalogous** [comment]
I'm planning to add DAC support to Firmata (at the protocol level) at some point: https://github.com/firmata/protocol/issues/32.

**Comment by fivdi** [comment]
@soundanalogous That sounds like a better way to go to me.

**Comment by soundanalogous** [comment]
This brings up another interesting question however which is how do we handle pin numbering with expander ICs?

**Comment by CzechUavGuy** [comment]
OK lets wait for soundanalogous for proper implementation. Then I can use his framework to rewrite my patch.

**Comment by rwaldron** [comment]
@fivdi thanks for intervening with that info

@soundanalogous re: pin numbering on ICs, if I understand your question correctly (which I might not), I generally stick to "as seen on the pcb"


I agree that once a "dacWrite" (or whatever) is designed, then this can follow.

**Comment by dtex** [comment]
The fix will have to wait on DAC support in firmata so I'm closing this PR. I've added the feature request to the [Requests Features](https://github.com/rwaldron/johnny-five/wiki/Requested-Features) wiki page and linked back to this PR.

**Pull request closed without merging**
