### PR TITLE
Added pre-commit. This is for issue #1490

### PR DESCRIPTION
**Pull request by matt611**

### CODE REVIEW

**Comment by matt611** [comment]
See pre-commit docs here: https://github.com/observing/pre-commit

**Comment by dtex** [comment]
Any idea why the operator on the version ranges in package-lock.json changed?

**Comment by dtex** [comment]
Here's the scoop https://github.com/npm/npm/issues/20434

There will be a lot of churn in the lock file on commits between users running npm v5 and v6.

**Comment by matt611** [comment]
Yeah, I'm not sure what the correct answer for the large package-lock.json diff is.  It seems like this will be the way going forward, but I'm happy to redo this commit with npm5 instead if that makes things easier.

**Pull request closed without merging**
