### PR TITLE
Fix error on code sample for Thermometer - LM35

### PR DESCRIPTION
**Pull request by Miguelerja**
I fixed a typo on the example code for the Thermometer - LM35 in the docs. The board event loop was started as function

### CODE REVIEW

**Comment by dtex** [comment]
Hi @Miguelerja 

Thank you for the catch and fix. One thing though, the md files in docs are generated by a script.

The [Writing Documentation](https://github.com/rwaldron/johnny-five/blob/master/CONTRIBUTING.md#writing-documentation) section of contributing.md covers how to do this (it's pretty easy to do, but also easy to miss).

**Comment by rwaldron** [comment]
@dtex @Miguelerja I can run the docs generator for this

**Comment by Miguelerja** [comment]
> @dtex @Miguelerja I can run the docs generator for this

Don't worry, I can check on that. Sorry for the confussion. I am fairly new to this

**Comment by rwaldron** [comment]
Merged https://github.com/rwaldron/johnny-five/commit/671434d32ba44f0daaa9875dea8f951eeb619496

**Pull request closed without merging**
