### PR TITLE
Fix Piezo.prototype.note()

### PR DESCRIPTION
**Pull request by islemaster**
_Re-opening #1324, which automatically closed when I merged https://github.com/code-dot-org/johnny-five/pull/3; see that PR for discussion.  Sorry about that! FYI @rwaldron @lyzadanger_

The `note()` method was passing a frequency (Hz) to the `tone()` method, which is expecting to receive a duty cycle (μs), leading to the wrong note being played.  The solution is for `note()` to call `frequency()` instead, which will do the appropriate conversion.

Since it took me a while to understand the relationships between `tone`, `frequency` and `note` I've added some documentation to those methods to clear things up for the next person.  I've also made some unit tests more aggressive about checking that values are converted appropriately as they're passed around, and commented note-frequency-duty equivalencies to help the test read nicer.

### CODE REVIEW

**Comment by islemaster** [comment]
Note: I'm not sure what's up with the failure in this test run and I'm unable to re-run tests on your repo, but I'm pretty sure it's flaky.  I've proposed some changes to help with test flakiness [over here](https://github.com/rwaldron/johnny-five/pull/1329).

**Comment by rwaldron** [comment]
@lyzadanger is this good to go? @islemaster addressed the test breakage in a different patch

**Comment by lyzadanger** [comment]
LGTM 👍

**Comment by rwaldron** [comment]
I will do a release asap.

**Pull request merged**
