### PR TITLE
Use correct Fritzing diagram to generate png

### PR DESCRIPTION
**Pull request by dtex**
This doesn’t have the curvy wires, but the pins numbers are right.

I'll let @Resseguie merge this one :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by rwaldron** [comment]
LGTM 

Land when Travis completes

**Comment by Resseguie** [comment]
The perfectionist in me wants to go through and give a common look-and-feel to all the fritzing diagrams!

**Comment by dtex** [comment]
The new ones do look really nice.

**Comment by rwaldron** [comment]
> The perfectionist in me wants to go through and give a common look-and-feel to all the fritzing diagrams!

This is what I spent much of January working on, but I still need help re-reviewing them all.

**Pull request merged**
