### PR TITLE
ESC: Update to controller model. Adds PCA9685. Closes gh-647

### PR DESCRIPTION
**Pull request by rwaldron**
cc @dtex

### CODE REVIEW

**Comment by rwaldron** [comment]
TODO: Update https://github.com/rwaldron/johnny-five/wiki/ESC when this lands

**Comment by rwaldron** [comment]
@dtex I'm going to wait on this one until your offset patch lands.

**Comment by dtex** [comment]
This looks really good to me. A few notes:

* Do we need to add deadband on ESC? I recall you were having a conversation with someone recently whose ESC didn't do anything from 51 - 54 (or something like that).
* Shouldn't the API for Motor and ESC be identical?
* I know the ESC class predates the controller model, but if I had a time machine I would make ESC a controller on Motor.
* PCA9685 support? **Bring on the hexadecicopters!**

> @dtex I'm going to wait on this one until your offset patch lands.

You are a kind man, but no need. That actual changes required for #666 (the bug from hell) are minimal so rebasing will be easy. I just need to get the logic right.

**Comment by rwaldron** [comment]
> Do we need to add deadband on ESC? I recall you were having a conversation with someone recently whose ESC didn't do anything from 51 - 54 (or something like that).

I'm waiting until I have a better understanding for bi-directional speed controllers. I think that makes a good follow up feature


> Shouldn't the API for Motor and ESC be identical?

I'll have a look, that might be a really good idea :)

> I know the ESC class predates the controller model, but if I had a time machine I would make ESC a controller on Motor.

Part of me agrees and part of me disagrees. I'm not sure which one to believe. 


> That actual changes required for #666 (the bug from hell) are minimal so rebasing will be easy. I just need to get the logic right.

Ok, sounds good.

**Pull request merged**
