### PR TITLE
Update color-convert to 1.2.2

### PR DESCRIPTION
**Pull request by Qix-**
Updated color-convert to the latest version.

Tests were already failing so not sure what was up there.

### CODE REVIEW

**Comment by rwaldron** [comment]
Looks like something is going on with `color-convert@1.2.2`, take a look: 

```

rwaldron at nova in ~/clonez/johnny-five on master*
$ grunt nodeunit
Running "nodeunit:tests" (nodeunit) task
Testing accelerometer.js..................OK
Testing animation.js..........OK
Testing altimeter.js....OK
Testing barometer.js.......OK
Testing board-connection.js.OK
Testing board.component.js...........................OK
Testing board.controller.js....OK
Testing board.js.........................................OK
Testing board.pins.js........OK
Testing button.js.........................OK
Testing capabilities.js.......OK
Testing collections.js................OK
Testing color.js.........OK
Testing compass.js..........OK
Testing esc.js.........................OK
Testing expander.js...........................................................................................................OK
Testing fn.js.........OK
Testing gps.js.........OK
Testing gyro.js.......OK
Testing hygrometer.js........OK
Testing imu.js...........................OK
Testing joystick.js..............OK
Testing keypad.js............................................................OK
Testing lcd.js...............................OK
Testing led.js.................................................................OK
Testing ledcontrol.js................................................................OK
Testing light.js........................OK
Testing motion.js..............................OK
Testing motor.js......................................................................................OK
Testing options.js.OK
Testing piezo.js....................OK
Testing pin.js.......................OK
Testing ping.js....OK
Testing pir.js.....OK
Testing proximity.js.................................................................OK
Testing reflectancearray.js............OK
Testing relay.js............OK
>> .OK
Testing sensor.js............................OK
Testing servo.js....................................OK
Testing shiftregister.js..................OK
Testing sonar.js........OK
Testing stepper.js...............................OK
Testing switch.js......OK
Testing thermometer.js.........................................................OK
Testing wii.js........OK
Testing within.js.....OK
>> 5914 assertions passed (10961ms)

Done, without errors.
rwaldron at nova in ~/clonez/johnny-five on master*
$ gco Qix--update-color-convert
Switched to branch 'Qix--update-color-convert'
rwaldron at nova in ~/clonez/johnny-five on Qix--update-color-convert*
$ npm install
johnny-five@0.9.37 /Users/rwaldron/clonez/johnny-five
└── color-convert@1.2.2

rwaldron at nova in ~/clonez/johnny-five on Qix--update-color-convert*
$ grunt nodeunit
Running "nodeunit:tests" (nodeunit) task
Fatal error: require(...) is not a function
```

**Comment by rwaldron** [comment]
Can you try the 1.3.1 release?

**Comment by Qix-** [comment]
Could you get a stacktrace for that by any chance?

**Comment by rwaldron** [comment]
Found it!

```
$ ./node_modules/grunt-contrib-nodeunit/node_modules/.bin/nodeunit  test
/Users/rwaldron/clonez/johnny-five/lib/lcd.js:4
  converter = require("color-convert")();
                                      ^

TypeError: require(...) is not a function
```

**Comment by Qix-** [comment]
Oh that's strange, such a weird error message. The major bump removed the otherwise ugly immediate call. Let me push a fix and see if that does it (for whatever reason tests are randomly failing on my box here).

**Comment by Qix-** [comment]
Give that a try.

**Comment by rwaldron** [comment]
And we're green! Thanks for that follow up :)


As an aside, I really appreciate module authors that seek out dependents of their work and make the effort to keep them updated :)

**Comment by Qix-** [comment]
Of course! A lot of effort and thought was put into the new API so I enjoy when people use it. :+1:

Thank you!!

**Pull request merged**
