### PR TITLE
Update led-rainbow.md

### PR DESCRIPTION
**Pull request by danielhep**
this.loop is not a function that exists... loop is a method in the temporal package.

### CODE REVIEW

**Comment by dtex** [comment]
I've been teaching J5 to some people who are new to Javascript, and I think the addition of Temporal would just confuse them.

@rwaldron Since [this](388866f110e7de748b3f06c04bd95a0aece2469d) was a breaking change can we just change Board.loop to use setInterval until the Temporal CPU issue is resolved?

**Comment by rwaldron** [comment]
@dtex the thing you linked to is 404'ing. 

@danielhep There is definitely a `loop` function defined on the `Board.prototype`:

```js
var five = require("../lib/johnny-five.js");
var board = new five.Board();

board.on("ready", function() {
  var index = 0;
  this.loop(5, function() {
    console.log(index++);

    if (index === 10) {
      process.exit();
    }
  });
});

```

Outputs:

```
rwaldron in ~/clonez/johnny-five on master
$ node eg/board-loop.js
1490977467864 Device(s) /dev/cu.usbmodem1411
1490977467884 Connected /dev/cu.usbmodem1411
1490977469606 Repl Initialized
>> 0
1
2
3
4
5
6
7
8
9
rwaldron in ~/clonez/johnny-five on master*
```

**Comment by dtex** [comment]
My link was just to the commit that commented out the Temporal based Board.loop. 

If I had scrolled a little further I would have seen where you had already put in a setInterval alternative.

**Comment by rwaldron** [comment]
Ah—gotcha :)

**Pull request closed without merging**
