### PR TITLE
Closes #1232

### LINKED ISSUE #1232: Basic Motor Example as Shown is Slightly Dangerous
http://johnny-five.io/examples/motor/

This could lead to melting an Arduino; circuit should have protective diode at least and external power optimally. 

I can take this as part of the motor-example work I'm doing but wanted to make sure there weren't any dissenters.

### PR DESCRIPTION
**Pull request by juventinoromero**
add protective diode to motor example. modify motor.fzz and motor.png

### CODE REVIEW

**Comment by dtex** [comment]
@juventinoromero It's not clear to me why you got this error since you did not change an eg or doc. Would you try running ```grunt examples``` and see what changes?

@lyzadanger Do you think we need to have the diode, resistor and transistor? Our goal is the simplest circuit that is still safe for the Arduino. The motors that ship with an Arduino Inventors Kit can usually be powered straight off PWM so you wouldn't necessarily need to the transistor and external power (though I think we should warn users that this configuration will only work for those tiny motors).

**Comment by lyzadanger** [comment]
> The motors that ship with an Arduino Inventors Kit can usually be powered straight off PWM so you wouldn't necessarily need to the transistor and external power (though I think we should warn users that this configuration will only work for those tiny motors).

I think that's the important distinction, though: lots (most?) motors draw too much current (especially inductive spikes) to be "safe" on, say, an Uno's 5V power pin. I know this was something that tripped me up when I was new to J5: I'd get crashes that felt random-ish because I was unknowingly using a servo that wanted too much current.

Not to complicate the issue, but what about two examples: one for low-voltage "micromotors" as it were and one for more beefier, normal motors (that second one could contain the extra components)?

**Comment by dtex** [comment]
> It's not clear to me why you got this error since you did not change an eg or doc

Ah, it was the copyright year.

**Comment by juventinoromero** [comment]
@dtex @lyzadanger I could do it with only the diode. It wouldn't be the best way to do it, but it's definitely better directly connecting the motor.

Also, do I need to change the copyright year to fix the build?

**Comment by dtex** [comment]
Normally you would just run ```grunt examples``` but since someone else has already landed the new generated examples it might be easier to rebase than deal with all the merge conflicts.

**Comment by rwaldron** [comment]
I fixed the build.

**Comment by juventinoromero** [comment]
@dtex @rwaldron thanks guys!

**Comment by dtex** [comment]
Thank you for the fix!

**Pull request merged**
