### PR TITLE
Update stepper-driver.md

### PR DESCRIPTION
**Pull request by deshawnbw**
This calls out that AdvancedFirmata should be used.

### CODE REVIEW

**Comment by rwaldron** [comment]
@deshawnbw Thanks for the contribution—unfortunately, you'll need to actually move the location of this message to `eg/stepper-driver.js`. The markdown files are all generated so your change will be lost on the next regen :\

**Comment by deshawnbw** [comment]
was a little too easy to edit via github, I'll put that in as a separate pull request then, thanks!

**Comment by rwaldron** [comment]
You can still edit `eg/stepper-driver.js` via github and I can do the regen when I land it

**Comment by soundanalogous** [comment]
You can also use the stepper motor with [ConfigurableFirmata](https://github.com/firmata/arduino/releases/tag/v2.6.2) however that requires the user to update the Firmata library within the Arduino application whereas AdvancedFirmata works with the version of Firmata that ships with Arduino. ConfigurableFirmata is also harder to use (since you need to currently manually configure it, but [work is in progress to automate this](https://github.com/firmata/firmata-builder)).

**Comment by rwaldron** [comment]
@soundanalogous thanks for the reminder and updated here https://github.com/rwaldron/johnny-five/commit/b05e95a45a717c78e7230f1acf6684a9a1c1b47b

**Pull request closed without merging**
