### PR TITLE
Match pins in LCD example to comments

### PR DESCRIPTION
**Pull request by stevekinney**
We played around with this for a while and couldn't get it working with the original version. After some research, this proposed change works. Coincidentally, it matches up with the commented documentation directly above it.

### CODE REVIEW

**Comment by rwaldron** [comment]
I'm mobile at the moment, so this isn't just me being lazy: does the fritzing diagram match the changes?

**Comment by rwaldron** [comment]
I just realized something else: the change needs to be made in the `eg/lcd.js` file, then run `grunt examples`, otherwise your change gets paved over.

**Comment by stevekinney** [comment]
Ah. I will check everything and let you know.

**Comment by rwaldron** [comment]
@stevekinney cool, and be sure to @ ping me when this is ready for a review :)

**Comment by rwaldron** [comment]
I updated the patch and set you as author. Landed: https://github.com/rwaldron/johnny-five/commit/9ad3e0fe7469a3322cbcd6b972317d20fffaec19

**Pull request closed without merging**
