### PR TITLE
Remove references to deprecated “axismove” event from Joystick examples

### PR DESCRIPTION
**Pull request by ChristophLabacher**
Fixes https://github.com/rwaldron/johnny-five/issues/1810

### CODE REVIEW

**Comment by dtex** [comment]
Awesome, thanks. There is just one more step that has to happen. There are .md files in the docs folder that get generated from the 'eg' files you edited. You have to run `grunt examples` for those to build, which must be done before I can merge. I could do it, but I'd rather use your PR.

**Comment by ChristophLabacher** [comment]
@dtex I just ran `grunt examples`,  but apparently none of the examples that I updated where used in the docs. However it seems like the command hasn’t been run in a long time and the copyright notices of all examples were updated.

**Comment by dtex** [comment]
I see that now. I'm so sorry. 

Maybe just delete that last commit and I'll get this merged?

**Comment by ChristophLabacher** [comment]
no worries 😊 removed the commit

**Pull request merged**
