### PR TITLE
Button pull-down support

### PR DESCRIPTION
**Pull request by andrewn**
As suggested in #1242 this adds support to the `Button` for enabling a pull-down resistor when `LOW` is written to an input pin on platforms that have them like the Raspberry Pi.

The corresponding [pull request](https://github.com/nebrius/raspi-io/issues/72) adds this behaviour to [Raspi-IO](https://github.com/nebrius/raspi-io).

### CODE REVIEW

**Comment by rwaldron** [comment]
This is supposed to be the default behavior of inputs, but I'm not opposed to allowing a mechanism that gives explicit control. We'll need to add a test—let me know if you'd like help with that

**Comment by andrewn** [comment]
Ah great, I didn't know that was default behaviour. On the Pi it needs to be explicitly enabled on a pin.

I'm happy to write a test but I can't quite figure out what it should be and where it should go so pointers would be useful please!

**Comment by rwaldron** [comment]
No worries, I don't mind writing the basic tests—that way you can see an example of what needs to be written for next time :)

**Comment by rwaldron** [comment]
Thanks!!

**Comment by andrewn** [comment]
No, thank you! 😄

**Pull request merged**
