### PR TITLE
[WIP] Prototype for DRYing out controller logic

### PR DESCRIPTION
**Pull request by scottgonzalez**
This is just to get some discussion going for #762. I've done some initial work for PCA9685 in `Led`/`Led.RGB`. Once we agree on the approach to take, I can do some work more and then update the tests.

There are a few questions written as TODOs in the controller file.

### CODE REVIEW

**Comment by dtex** [comment]
Me gusto mucho.

Do we have a list of other controllers? 
How does this relate to expanders?
Does the PCA9685 ever accept anything besides 12-bit values? (this removes the ability to set PWM range)

**Comment by scottgonzalez** [comment]
> Do we have a list of other controllers?

I can put a list together by searching for "var Controllers". I think many of them are actually component-specific so this abstraction wouldn't need to be applied to them. I'll go through and see which ones are used by more than one component.

> How does this relate to expanders?

At least based on the current design of Johnny-Five, users initialize the expanders themselves. This would only apply to the existing `controller` option within the individual components. Perhaps PCA9685 is just an odd case?

> Does the PCA9685 ever accept anything besides 12-bit values? (this removes the ability to set PWM range)

The PWM range will be supported once I get to a controller that doesn't use the full range. I know at least servo uses a different range.

**Comment by rwaldron** [comment]
My plan was to use instances of `Expander` wherever possible; I have a bunch of work completed for migrating the PCA9685 (just that so far), but it's all in a git stash. I don't want another new PCA9685 thing.

**Comment by rwaldron** [comment]
Out of the stash, committed, rebased, etc... https://github.com/rwaldron/johnny-five/commits/controllers-can-use-expanders

**Pull request closed without merging**
