### PR TITLE
Test for "move:complete"

### PR DESCRIPTION
**Pull request by deathbearbrown**
Test for calling emit "move:complete" in the case where you call the same degree value twice.
Sorry the last PR got merged faster than I could add this. 

For testing this line:
https://github.com/rwaldron/johnny-five/blob/master/lib/servo.js#L286

### CODE REVIEW

**Comment by dtex** [comment]
This test fails in an unhelpful way. It will eventually time out and return ```Fatal error: Uncaught, unspecified "error" event.``` I wonder if there is a better way?

**Comment by rwaldron** [comment]
```
$ grunt
Running "jshint:files" (jshint) task
>> 292 files lint free.

Running "jscs:files" (jscs) task
Missing space before opening curly brace for block expressions at test/servo.js :
   191 |    this.servo.to(180);
   192 |    this.servo.to(180, 1000, 100);
   193 |    this.servo.on("move:complete", function(){
----------------------------------------------------^
   194 |      test.ok(this.servoWrite.callCount,1);
   195 |      test.done();
>> 1 code style errors found!
Warning: Task "jscs:files" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by rwaldron** [comment]
@dtex when the event isn't emitted? I've been trying to track that error event down and I can't find it. I also can't figure out how to intercept the timeout.

**Comment by deathbearbrown** [comment]
I can't figure out how to test this right.  

@rwaldron suggested that I should wrap the event in process.nextTick(), but if I remove it & put a console.log() inside the .on('move:Complete') in the test, it never gets in there.

**Comment by rwaldron** [comment]
This is maybe a dumb question: were you using "move:complete" or "move:Complete"?

**Comment by deathbearbrown** [comment]
Not a dumb question. It's just 'move:complete'  I made a typo.

**Comment by rwaldron** [comment]
Ok cool (that's what I figured, but never hurts to ask)

**Comment by rwaldron** [comment]
@dtex neither of us can figure out how to intercept that error. The only consequence of accepting this patch without a nicer error is that it's hard to figure out what happened if `process.nextTick(this.emit.bind(this, "move:complete"));` is ever removed—which it shouldn't be anyway. I'm willing to accept this consequence.

**Comment by dtex** [comment]
Agreed. It should never happen and the test will fail if it does which is the most important thing. Plus it'll be pretty easy to track down if it ever does come up.

**Pull request merged**
