### PR TITLE
Update the led pulse example

### PR DESCRIPTION
**Pull request by kisPocok**
The guide image shows port 13. Let's use that.

### CODE REVIEW

**Comment by dtex** [comment]
Hi @kisPocok ,

the MarkDown files in /docs are generated from the js files in /eg. Make your edit to eg/led-pulse.js and then run ```grunt examples```.

**Comment by kisPocok** [comment]
Yeah, I got it after the test failed. I will update it soon, please revert/refuse this changes.

**Comment by dtex** [comment]
New PR #660

**Comment by Resseguie** [comment]
It actually needs to be 9 because 13 isn't PWM. It's the diagram that needs to be updated.

**Comment by dtex** [comment]
We should re-open #660 instead. This one was never merged.

I'm a one man 3 Stooges act right now. Excuse me while I go poke myself in the eye.

**Comment by kisPocok** [comment]
Sorry for the trouble. I didn't know that, thanks for the heads up!

**Comment by Resseguie** [comment]
No problem. The examples have been created somewhat haphazard along the way so it's always good to have extra sets of eyes. I'd like to go through and check them all for consistency, style, etc.

**Comment by rwaldron** [comment]
>:|


Start here and move forward in time: https://github.com/rwaldron/johnny-five/commits/master?page=5

I reviewed every single example and remade most of them, the problem is that the task is time consuming and mind numbing and it's often easy to reuse the same diagram for similar examples. 

Yes, another set of eyes.

**Comment by Resseguie** [comment]
Oh good, it looks like you've done the hard work already! Cool. I haven't reviewed them since that update. I'll make a note to do a sanity check pass-through.

**Comment by rwaldron** [comment]
Yes, please do. More eyes are better. Also, some examples may be missing diagrams, these need to be created

**Pull request closed without merging**
